version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5431:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=labrute